package com.movem.backend.model.enums.Activity;

public enum ActivityFeedEvent {

    TASK_CREATED,
    TASK_UPDATED,
    TASK_COMPLETED,
    TASK_DELETED,
    TASK_RESTORED,

    CHECKLIST_ADDED,
    CHECKLIST_UPDATED,
    CHECKLIST_COMPLETED,
    CHECKLIST_REMOVED,

    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,

    FRIEND_REQUEST_SENT,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,
    FRIEND_REMOVED,

    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,

    INVITE_ACCEPTED,
    INVITE_REJECTED,

    MEMBER_INVITED,
    MEMBER_JOINED,
    MEMBER_LEFT,
    MEMBER_REMOVED,

    JOIN_REQUEST_SENT,
    JOIN_REQUEST_APPROVED,
    JOIN_REQUEST_REJECTED,

    DEADLINE_CHANGED,

    LABEL_ADDED,
    LABEL_REMOVED,

    ACTIVITY_SOFT_DELETED,
    ACTIVITY_RESTORED,
    ACTIVITY_HARD_DELETED,

}