package com.movem.backend.model.enums.Activity;

import com.movem.backend.model.enums.Audit.AuditCategory;

public enum ActivityFeedEvent {

    TASK_CREATED,
    TASK_UPDATED,
    TASK_COMPLETED,
    TASK_DELETED,
    TASK_RESTORED,
    TASK_RECURRED,

    CHECKLIST_ADDED,
    CHECKLIST_UPDATED,
    CHECKLIST_COMPLETED,
    CHECKLIST_REMOVED,

    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,

    FRIEND_REQUEST_SENT,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,
    FRIEND_REMOVED,

    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,

    INVITE_ACCEPTED,
    INVITE_REJECTED,

    MEMBER_INVITED,
    MEMBER_JOINED,
    MEMBER_LEFT,
    MEMBER_UPDATED,
    MEMBER_REMOVED,

    JOIN_REQUEST_SENT,
    JOIN_REQUEST_APPROVED,
    JOIN_REQUEST_REJECTED,

    DEADLINE_CHANGED,

    LABEL_ADDED,
    LABEL_REMOVED,

    CHALLENGE_CREATED,
    CHALLENGE_UPDATED,
    CHALLENGE_STARTED,
    CHALLENGE_COMPLETED,
    CHALLENGE_JOINED,
    CHALLENGE_LEFT,
    CHALLENGE_CANCELLED,
    CHALLENGE_REMOVED,

    WORKOUT_COMPLETED,
    WORKOUT_KUDOED,
    WORKOUT_KUDO_REMOVED,

    ACTIVITY_SOFT_DELETED,
    ACTIVITY_RESTORED,
    ACTIVITY_HARD_DELETED,

    TRIP_CREATED,
    TRIP_UPDATED,
    TRIP_DELETED,
    TRIP_RESTORED,
    STOP_ADDED,
    STOP_COMPLETED,
    EXPENSE_LOGGED,

}