spring.application.name=movem-backend


# Data Database Configuration
#spring.datasource.url=jdbc:mysql://movem-mysql-service:3306/movem
spring.datasource.url=jdbc:mysql://localhost:3306/movem_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# HikariCP Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# JWT Configuration
# 24 hours in milliseconds
app.jwt.expiration=86400000
# Replace this with your own long Base64 string!
# (You can generate one using an online Base64 generator)
app.jwt.secret=${JWT_SECRET}

# Trust Tokens
app.jwt.trust-expiration=259200000

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
spring.mail.username=sanghourjr@gmail.com
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method